-- BodyFix Pulse v1. Prefixes avoid collisions with existing BodyFix OS tables.
create extension if not exists pgcrypto;
create table if not exists pulse_settings (id uuid primary key default gen_random_uuid(), month_target integer not null default 150000, period_start date not null default date_trunc('month', now() at time zone 'Asia/Taipei')::date, period_end date not null default (date_trunc('month', now() at time zone 'Asia/Taipei') + interval '1 month - 1 day')::date, rest_weekdays integer[] default '{2}', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists pulse_income_entries (id uuid primary key default gen_random_uuid(), entry_date date not null, client_name text, service_type text, amount integer not null default 0 check(amount >= 0), source text, note text, created_at timestamptz default now());
create table if not exists pulse_appointments (id uuid primary key default gen_random_uuid(), appointment_date date not null, start_time time, client_name text, service_type text, estimated_amount integer, status text default '已排' check(status in ('已排','待確認','已完成','取消')), note text, created_at timestamptz default now());
create table if not exists pulse_followups (id uuid primary key default gen_random_uuid(), client_name text not null, last_visit_date date, main_issue text, contact_method text, priority text default '中' check(priority in ('高','中','低')), followup_status text default '未聯絡' check(followup_status in ('未聯絡','已聯絡','已回覆','已預約','暫不打擾')), suggested_message text, created_at timestamptz default now());
create index if not exists pulse_income_date_idx on pulse_income_entries(entry_date); create index if not exists pulse_appointment_date_idx on pulse_appointments(appointment_date,status);
alter table pulse_settings enable row level security; alter table pulse_income_entries enable row level security; alter table pulse_appointments enable row level security; alter table pulse_followups enable row level security;
insert into pulse_settings(month_target) select 150000 where not exists(select 1 from pulse_settings);
