BEGIN;

CREATE TABLE IF NOT EXISTS public.taipei_zone_registrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL DEFAULT 'bodyfix',
  preferred_zone text NOT NULL,
  liuzhangli_distance_feeling text NOT NULL,
  main_need text NOT NULL,
  session_length_preference text NOT NULL,
  service_mode text NOT NULL,
  preferred_time text[] NOT NULL DEFAULT '{}',
  is_existing_client text NOT NULL DEFAULT 'unknown',
  contact_type text NOT NULL,
  contact_value text NOT NULL,
  note text,
  status text NOT NULL DEFAULT 'new',
  intent_level text NOT NULL DEFAULT 'normal',
  source text NOT NULL DEFAULT 'taipei_zone_page',
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT taipei_zone_preferred_zone_valid CHECK (preferred_zone IN ('ximen','liuzhangli','sun_yat_sen_memorial_hall','home_visit','other')),
  CONSTRAINT taipei_zone_distance_feeling_valid CHECK (liuzhangli_distance_feeling IN ('convenient','acceptable','a_bit_far','too_far_affects_booking')),
  CONSTRAINT taipei_zone_main_need_valid CHECK (main_need IN ('neck_shoulder_chest','lower_back_pelvis','hip_legs','training_recovery','movement_training','twelve_session_plan','ziwei_tarot','other')),
  CONSTRAINT taipei_zone_session_length_valid CHECK (session_length_preference IN ('sixty_main','sixty_plus_30_if_needed','consult_first')),
  CONSTRAINT taipei_zone_service_mode_valid CHECK (service_mode IN ('studio','home_visit','flexible','consult_first')),
  CONSTRAINT taipei_zone_existing_client_valid CHECK (is_existing_client IN ('yes','no','unknown')),
  CONSTRAINT taipei_zone_contact_type_valid CHECK (contact_type IN ('line','instagram','phone','other')),
  CONSTRAINT taipei_zone_status_valid CHECK (status IN ('new','contacted','converted_to_booking','not_now','invalid')),
  CONSTRAINT taipei_zone_intent_level_valid CHECK (intent_level IN ('low','normal','high','vip'))
);

CREATE INDEX IF NOT EXISTS idx_taipei_zone_registrations_zone ON public.taipei_zone_registrations (preferred_zone);
CREATE INDEX IF NOT EXISTS idx_taipei_zone_registrations_created_at ON public.taipei_zone_registrations (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_taipei_zone_registrations_intent ON public.taipei_zone_registrations (intent_level);
CREATE INDEX IF NOT EXISTS idx_taipei_zone_registrations_status ON public.taipei_zone_registrations (status);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_taipei_zone_registrations_updated_at ON public.taipei_zone_registrations;
CREATE TRIGGER trg_taipei_zone_registrations_updated_at
BEFORE UPDATE ON public.taipei_zone_registrations
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE VIEW public.taipei_zone_summary AS
SELECT
  preferred_zone,
  COUNT(*)::integer AS total_count,
  COUNT(*) FILTER (WHERE liuzhangli_distance_feeling IN ('a_bit_far', 'too_far_affects_booking'))::integer AS distance_friction_count,
  COUNT(*) FILTER (WHERE intent_level IN ('high', 'vip'))::integer AS high_intent_count,
  COUNT(*) FILTER (WHERE session_length_preference = 'sixty_plus_30_if_needed')::integer AS plus_30_interest_count,
  COUNT(*) FILTER (WHERE session_length_preference = 'sixty_main')::integer AS sixty_main_count,
  COUNT(*) FILTER (WHERE service_mode = 'home_visit')::integer AS home_visit_count,
  COUNT(*) FILTER (WHERE main_need = 'twelve_session_plan')::integer AS twelve_session_interest_count,
  COUNT(*) FILTER (WHERE main_need = 'movement_training')::integer AS movement_training_interest_count,
  COUNT(*) FILTER (WHERE is_existing_client = 'yes')::integer AS existing_client_count,
  MAX(created_at) AS latest_registration_at,
  CASE
    WHEN preferred_zone = 'ximen' AND COUNT(*) >= 5 THEN 'can_open_full_day'
    WHEN preferred_zone = 'ximen' AND COUNT(*) >= 3 THEN 'can_open_half_day'
    WHEN preferred_zone = 'sun_yat_sen_memorial_hall' AND COUNT(*) >= 3 THEN 'can_test_evening'
    WHEN preferred_zone = 'home_visit' AND COUNT(*) >= 3 THEN 'vip_only_review'
    WHEN preferred_zone = 'liuzhangli' THEN 'home_base'
    ELSE 'observe'
  END AS suggested_action
FROM public.taipei_zone_registrations
WHERE status <> 'invalid'
GROUP BY preferred_zone;

CREATE TABLE IF NOT EXISTS public.taipei_zone_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL UNIQUE,
  value text NOT NULL,
  note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT taipei_zone_settings_status_valid CHECK (
    key <> 'public_status' OR value IN ('coming_soon','registration_open','closed')
  )
);

INSERT INTO public.taipei_zone_settings (key, value, note)
VALUES ('public_status','registration_open','Taipei zone registration public frontend state')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();

GRANT USAGE ON SCHEMA public TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.taipei_zone_registrations TO service_role;
GRANT SELECT ON public.taipei_zone_summary TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.taipei_zone_settings TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

NOTIFY pgrst, 'reload schema';

COMMIT;
