"use client";
import { useParams } from "next/navigation";
import { ClinicNotice, ClinicShell, planLabels, stageLabels, useClinicFetch } from "@/components/clinic/ClinicShell";
type Data = { summary: any; records: any[]; plan_candidates: any[] };
export default function ClientSummaryPage() {
  const { id } = useParams<{ id: string }>();
  const { data, loading, error } = useClinicFetch<Data>(`/api/clinic/clients/${id}/summary`);
  return <ClinicShell title="去識別化摘要 / 列印頁" subtitle="此頁不可顯示姓名、電話、LINE ID、Instagram、生日或完整地址。"><ClinicNotice loading={loading} error={error} />{data && <section className="bf-card bf-section-gap clinic-print"><h2>【BodyFix 客戶摘要｜去識別化】</h2><p>客戶代號：{data.summary.client_code}</p><p>城市：{data.summary.city ?? "—"}</p><p>目前階段：{stageLabels[data.summary.current_stage] ?? data.summary.current_stage}</p><p>主要困擾：{data.summary.main_issue ?? "—"}</p><h3>近期服務紀錄：</h3>{data.records.map((r, index) => <div className="clinic-item" key={`${r.service_date}-${index}`}><strong>{index + 1}. {r.service_date}｜{r.service_name_snapshot ?? r.service_code ?? "服務"}｜{r.duration_minutes ?? "—"} 分</strong><span>判讀：{r.fatigue_state_assessment ?? r.main_complaint ?? "—"}</span><span>整理：{r.processed_area ?? r.strategy ?? "—"}</span><span>反應：{r.client_reaction ?? "—"}</span><span>整理後變化：{r.after_change ?? "—"}</span><span>下次重點：{r.next_focus ?? "—"}</span></div>)}<p>常見模式：{data.records.map((r) => r.main_tension_area).filter(Boolean).join("、") || "—"}</p><p>常處理區域：{data.records.map((r) => r.body_region ?? r.processed_area).filter(Boolean).join("、") || "—"}</p><p>目前進度：總來訪 {data.summary.total_sessions ?? 0} 次，最近服務 {data.summary.last_session_date ?? "—"}。</p><p>下一步建議：{data.plan_candidates.map((p) => `${planLabels[p.suggested_plan_type] ?? p.suggested_plan_type}：${p.suggested_pitch ?? p.trigger_reason ?? p.status}`).join("；") || "持續觀察整理後反應。"}</p><button className="bf-small-btn no-print" type="button" onClick={() => window.print()}>列印</button></section>}</ClinicShell>;
}
