"use client";
import Link from "next/link";
import { useState } from "react";
import BodyTensionHeroMap, { type BodyTensionMapType } from "../../../components/tests/BodyTensionHeroMap";

type Kind = "A" | "B" | "C" | "D";
type IconName = "back" | "pelvis" | "breath" | "balance" | "core" | "walk" | "pause" | "move" | "recover";
type Result = { mapType:BodyTensionMapType; short:string; title:string; resonance:string; copy:string; zones:string[]; feelings:{icon:IconName;text:string}[]; actions:{icon:IconName;title:string;copy:string}[]; service:string; serviceId:string; reason:string };
const questions: { title: string; options: Record<Kind, string> }[] = [
  { title: "你每天大部分時間，身體比較像哪種狀態？", options: { A:"長時間坐著工作或滑手機，幾乎不動", B:"雖然有活動，但肩頸、胸口或小腿常緊繃", C:"有固定訓練或運動，但訓練後恢復比較慢", D:"感覺身體某側或某部位特別用力，動作時容易不對稱" } },
  { title: "最近你最常注意到的身體感覺是？", options: { A:"肩頸僵硬、腰部或下背痠", B:"呼吸比較淺，胸口或肚子容易緊", C:"訓練或活動後，某個部位特別容易痠痛或僵硬", D:"骨盆、髖關節或下背感覺不穩，站久或走路時容易代償" } },
  { title: "你對「放鬆」或「休息」的感覺是？", options: { A:"坐下來休息後，身體某些地方還是放不開", B:"想放鬆，但容易一直想事情，身體像保持警戒", C:"休息後有恢復，但下次訓練還是容易回到緊繃", D:"想放鬆時，骨盆或核心區域反而更容易用力" } },
  { title: "你平常最常出現的「卡住」感覺在哪裡？", options: { A:"脖子、肩膀、上背", B:"胸口、呼吸、腹部", C:"訓練後的肌肉或筋膜，例如大腿、小腿、肩胛", D:"骨盆、髖關節、下背或核心區域" } },
  { title: "你對自己身體的整體感覺最接近哪一句？", options: { A:"久坐後容易僵硬，需要常常活動才舒服", B:"壓力或情緒一來，身體就容易進入緊繃模式", C:"訓練熱情高，但恢復速度跟不上，容易累積疲勞", D:"感覺身體某些動作順序錯了，核心或骨盆不太穩" } },
];
const sharedActions:{icon:IconName;title:string;copy:string}[]=[{icon:"pause",title:"先不要急著狂拉筋",copy:"先觀察哪裡在硬撐，不直接拉最卡的地方。"},{icon:"breath",title:"做 3 分鐘呼吸",copy:"感覺肋骨、腹部與骨盆能不能一起動。"},{icon:"walk",title:"散步 5 分鐘",copy:"用舒服節奏，讓張力重新分工。"}];
const results: Record<Kind, Result> = {
 A:{mapType:"sedentary",short:"久坐型",title:"久坐型｜身體被同一個姿勢綁太久",resonance:"不是你沒在動，是身體被同一個姿勢鎖太久。",copy:"長期維持同一個姿勢，肩頸、上背、髖屈肌與下背容易累積張力。起身時會覺得身體慢半拍、卡卡的。",zones:["肩頸","上背","髖部","下背"],feelings:[{icon:"back",text:"肩頸、上背容易僵硬"},{icon:"pelvis",text:"髖前側像縮在一起"},{icon:"back",text:"坐久後下背容易痠"},{icon:"walk",text:"起身走動才比較舒服"}],actions:[{icon:"walk",title:"每 45 分鐘起身",copy:"走動 2 分鐘，先打破固定姿勢。"},{icon:"move",title:"髖關節開合 10 次",copy:"小幅度、可呼吸地讓髖重新動。"},{icon:"breath",title:"做 3 分鐘呼吸",copy:"讓肋骨與背部也參與呼吸。"}],service:"筋膜鏈整理｜60 分鐘｜NT$2,200",serviceId:"fascia_chain_reset_60",reason:"適合久坐後肩頸、上背、髖與下背一起卡住的人。"},
 B:{mapType:"stress",short:"壓力型",title:"壓力型｜身體一直處在警戒模式",resonance:"你不是懶得放鬆，是身體還沒解除警戒。",copy:"壓力、情緒或睡眠不足時，呼吸、胸口與腹部容易先進入保護性緊繃。先讓身體感到安全，才有空間慢慢鬆開。",zones:["肩頸","胸口","呼吸","腹部"],feelings:[{icon:"breath",text:"呼吸容易變淺"},{icon:"back",text:"肩頸不自覺抬起"},{icon:"core",text:"胸口或腹部容易緊"},{icon:"pause",text:"休息時仍像在警戒"}],actions:[{icon:"breath",title:"延長吐氣 3 分鐘",copy:"不用吸很深，先把吐氣放慢。"},{icon:"pause",title:"放下肩膀與下巴",copy:"確認自己沒有一直默默出力。"},{icon:"walk",title:"慢走 5 分鐘",copy:"不追速度，找回舒服節奏。"}],service:"筋膜鏈整理｜60 分鐘｜NT$2,200",serviceId:"fascia_chain_reset_60",reason:"適合壓力一來，胸口、腹部、肩頸就跟著緊的人。"},
 C:{mapType:"training",short:"訓練恢復型",title:"訓練恢復型｜練得夠，但恢復跟不上",resonance:"練得夠多，但身體還在追趕恢復的進度。",copy:"訓練後某些筋膜線容易累積張力，局部代償變多，熱身要很久才打得開，疲勞感也比較容易堆積。",zones:["肩胛","髖部","大腿","腿後側"],feelings:[{icon:"recover",text:"運動後僵硬留很久"},{icon:"back",text:"肩胛附近容易卡"},{icon:"pelvis",text:"髖活動感不平均"},{icon:"balance",text:"同一側反覆疲勞"}],actions:[{icon:"pause",title:"今天降低一點強度",copy:"讓身體有時間消化訓練刺激。"},{icon:"move",title:"做溫和活動恢復",copy:"小範圍動一動，不追求拉到底。"},{icon:"breath",title:"呼吸整合 3 分鐘",copy:"確認訓練後仍能舒服呼吸。"}],service:"筋膜線指定整理｜60 分鐘｜NT$2,300",serviceId:"fascia_line_selected_reset_60",reason:"適合訓練後特定區域一直卡、左右不平均、某條線一直緊的人。"},
 D:{mapType:"pelvic",short:"骨盆核心代償型",title:"骨盆核心代償型｜核心沒有穩，其他地方先硬撐",resonance:"核心還沒穩住，其他地方就先硬撐起來了。",copy:"骨盆與核心的分工暫時沒有接好，髖或下背便容易搶著出力。先找回呼吸與骨盆的協調，不是哪裡痠就只按哪裡。",zones:["骨盆","核心","髖關節","下背"],feelings:[{icon:"back",text:"下背容易痠"},{icon:"pelvis",text:"髖或骨盆容易卡"},{icon:"balance",text:"單側發力不順"},{icon:"core",text:"核心練很多仍不穩"},{icon:"breath",text:"呼吸與骨盆難協調"}],actions:[{icon:"pause",title:"先不要急著狂拉筋",copy:"先觀察哪裡在硬撐，不直接拉最卡的地方。"},{icon:"pelvis",title:"骨盆前後傾 10 次",copy:"用小幅度找回骨盆中立位置。"},{icon:"breath",title:"3 分鐘呼吸練習",copy:"感覺肋骨、腹部和骨盆一起動。"}],service:"骨盆核心整理｜60 分鐘｜NT$2,500",serviceId:"pelvic_core_reset_60",reason:"適合骨盆、髖、下背、核心代償與呼吸卡住的人。"},
};
function LineIcon({name}:{name:IconName}){const paths:Record<IconName,string>={back:"M10 4c3 2 3 5 3 8s-1 6 1 8M7 8h6M7 16h7",pelvis:"M5 8c1 7 3 10 7 10s6-3 7-10M7 9c2 2 8 2 10 0M12 11v7",breath:"M11 5v6c-2-3-6-3-7 2-1 4 2 6 7 6M13 5v6c2-3 6-3 7 2 1 4-2 6-7 6",balance:"M4 12h16M8 8l-4 4 4 4M16 8l4 4-4 4",core:"M12 4c-5 0-7 3-7 8s2 8 7 8 7-3 7-8-2-8-7-8Zm0 5v6m-3-3h6",walk:"M13 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm-2 4-3 4-3 1m6-5 3 4 4 1m-7-1-2 7m3-6 4 6",pause:"M9 7v10m6-10v10M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Z",move:"M5 12h14m-3-3 3 3-3 3M8 7 5 12l3 5",recover:"M18 8a7 7 0 1 0 1 7M18 4v4h-4"};return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]}/></svg>}
const flow=[['01','判讀','Read'],['02','整理','Reset'],['03','整合','Reconnect'],['04','接回使用','Return']];
export default function BodyTensionPage(){const [answers,setAnswers]=useState<Partial<Record<number,Kind>>>({});const [done,setDone]=useState(false);const [copied,setCopied]=useState(false);const scores={A:0,B:0,C:0,D:0};Object.values(answers).forEach(x=>{if(x)scores[x]++});const ranked=(Object.keys(scores) as Kind[]).sort((a,b)=>scores[b]-scores[a]);const max=scores[ranked[0]];const winners=ranked.filter(k=>scores[k]===max);const primary=winners[0];const secondary=winners[1];const mixed=winners.length>1;const feelings=mixed?[...results[primary].feelings.slice(0,2),...results[secondary].feelings.slice(0,2)]:results[primary].feelings;const actions=mixed?sharedActions:results[primary].actions;const copyResult=async()=>{await navigator.clipboard.writeText(`${mixed?`混合型｜${results[primary].short} + ${results[secondary].short}`:results[primary].title}\n${results[primary].copy}`);setCopied(true);setTimeout(()=>setCopied(false),1800)};
return <main className="tension-page"><div className="tension-shell"><nav className="tests-nav"><Link className="portal-wordmark" href="/"><span>BF</span><strong>BodyFix OS</strong></Link><div><Link href="/tests">所有測驗</Link></div></nav>
{!done&&<header className="tension-hero"><p className="portal-kicker">BODY STATE CHECK · 5 QUESTIONS</p><h1>你是哪一種硬撐型身體？</h1><p>久坐、壓力、訓練恢復、骨盆核心代償。5 題看你現在的身體，是哪裡正在默默硬撐。</p></header>}
{!done ? <section className="tension-quiz">{questions.map((q,i)=><fieldset className="tension-question" key={q.title}><legend><span>0{i+1}</span>{q.title}</legend><div>{(Object.entries(q.options) as [Kind,string][]).map(([key,text])=><label className={answers[i]===key?"selected":""} key={key}><input type="radio" name={`q${i}`} checked={answers[i]===key} onChange={()=>setAnswers({...answers,[i]:key})}/><b>{key}</b><span>{text}</span></label>)}</div></fieldset>)}<button className="tension-submit" disabled={Object.keys(answers).length!==questions.length} onClick={()=>{setDone(true);scrollTo({top:0,behavior:"smooth"})}}>看我的張力傾向 <span>→</span></button></section> : <section className="tension-report">
<section className="report-hero"><div><p className="portal-kicker">YOUR BODY TENSION REPORT</p>{mixed&&<span className="result-badge">混合型 · 主型態</span>}<h1>{mixed?`混合型｜${results[primary].short} + ${results[secondary].short}`:results[primary].title}</h1><p className="report-resonance">{results[primary].resonance}</p><p>{results[primary].copy}</p>{mixed&&<p className="secondary-note"><b>{results[secondary].short}</b>也正在參與這次的張力分工。</p>}</div><BodyTensionHeroMap type={results[primary].mapType} secondaryType={mixed?results[secondary].mapType:undefined}/></section>
<section className="report-section"><div className="report-heading"><span>01 · BODY SIGNALS</span><h2>你可能會出現的身體感覺</h2><p>這些是張力傾向，不是醫療診斷。</p></div><div className="feeling-grid">{feelings.map((f,i)=><div className="feeling-card" key={`${f.text}-${i}`}><LineIcon name={f.icon}/><span>{mixed&&<small>{i<2?results[primary].short:results[secondary].short}</small>}{f.text}</span></div>)}</div></section>
<section className="report-section"><div className="report-heading"><span>02 · START TODAY</span><h2>今天可以先做的 3 件事</h2><p>不追求痛、不做到極限，從身體能接受的深度開始。</p></div><div className="action-grid">{actions.map((a,i)=><article className="action-card" key={a.title}><div><b>0{i+1}</b><LineIcon name={a.icon}/></div><h3>{a.title}</h3><p>{a.copy}</p></article>)}</div></section>
<section className="report-section process-section"><div className="report-heading"><span>03 · BODYFIX 4R</span><h2>BodyFix 會怎麼整理這一型</h2><p>不是哪裡痠就只按哪裡，而是先看張力怎麼分工，再用低痛感、可呼吸、身體能接受的深度，把身體接回使用。</p></div><div className="flow-grid">{flow.map(([n,zh,en])=><div key={n}><b>{n}</b><span>{zh}<small>{en}</small></span></div>)}</div></section>
<section className="service-card"><div><span>推薦服務 · FOR YOUR BODY</span><h2>{results[primary].service}</h2><p>{results[primary].reason}</p></div><Link href={`/booking?service=${results[primary].serviceId}&source=body-tension`}>預約{results[primary].service.split("｜")[0]} <span>→</span></Link></section>
<div className="report-footer"><button onClick={copyResult}>{copied?"已複製結果 ✓":"複製我的結果"}</button><button onClick={()=>{setAnswers({});setDone(false);setCopied(false);scrollTo({top:0,behavior:"smooth"})}}>重新測一次</button><Link href="/tests">回測驗首頁</Link></div></section>}</div></main>}
