import Link from "next/link";

const framework = [
  ["01", "Read", "判讀", "從主訴、呼吸、站姿與動作回測，理解目前的張力如何分工。", "Observe · Compare · Record"],
  ["02", "Reset", "整理", "在低痛感、可呼吸、身體能接受的深度裡，降低不必要的張力與保護性收縮。", "Low Pain · Breathable · Adaptive"],
  ["03", "Reconnect", "整合", "把呼吸、足底、軀幹與筋膜線重新接回簡單動作。", "Breath · Ground · Movement"],
  ["04", "Return", "接回使用", "透過回測、紀錄與後續追蹤，確認新的身體策略能否被保留下來。", "Apply · Track · Progress"],
];
const routes = [
  { label: "Route A｜方法認識", en: "METHOD INTRODUCTION", fit: ["尚未具備徒手操作基礎", "想理解 BodyFix 的 4R、判讀與安全邊界", "健身教練想先了解身體狀態觀察與回測"], content: ["4R 核心流程", "身體狀態基礎觀察", "張力分工概念", "安全與服務界線"], result: "參與紀錄", note: "不包含完整徒手技術，不等於實作合格、認證或授權。", button: "了解方法介紹", href: "/method/pathway" },
  { label: "Route B｜能力銜接", en: "FOUNDATION BRIDGE", fit: ["健身教練補強徒手接觸與操作安全", "按摩工作者補強動作觀察與回測", "身體工作者補強紀錄與服務界線"], content: ["基礎解剖與定位", "運動按摩基本操作", "接觸、壓力與身體重心", "主觀回報與異常反應", "動作回測與服務紀錄"], result: "先備能力確認", note: "COMING SOON", button: "查看能力銜接", href: "/method/pathway" },
  { label: "Route C｜BodyFix 方法實作", en: "BODYFIX METHOD PRACTICE", fit: ["已具備徒手接觸與安全操作能力", "能辨認主要解剖位置", "能做基本動作觀察與回測", "希望進入筋膜線、張力分工與完整 4R 應用"], content: ["Read 判讀", "Reset 整理", "Reconnect 整合", "Return 接回使用", "單線至多線整合", "案例記錄與實作評量"], result: "完課與實作評量依正式課程規格另行公布", note: "COMING SOON", button: "關注進階路線", href: "/method/register" },
];
const outcomes = ["理解 4R 如何串起觀察、整理、整合與回測。", "知道如何用主訴、呼吸、站姿與動作回測建立服務紀錄。", "辨認安全邊界、停止條件與需要轉介或建議就醫的情況。", "依照自身背景選擇方法認識、能力銜接或方法實作路線。"];

export default function MethodPage() {
  return <main className="portal-page portal-detail-page method-page"><div className="portal-detail-shell method-shell"><Link className="portal-back-link" href="/learning">← 返回 Learning Portal</Link><header className="portal-detail-hero method-hero"><p className="portal-kicker">BODYFIX METHOD LEARNING PORTAL</p><h1>BodyFix Method</h1><p className="portal-detail-lead">很多人以為，身體工作靠的是手感。</p><p className="method-hero-intro">真正困難的，是把觀察與判讀說清楚、把操作做穩定，並讓每一次整理都能被記錄、回測與延續。BodyFix Method，就是把現場經驗整理成一套可判讀、可執行、可記錄的方法系統。</p><p className="method-emphasis">不是把力道做得更重，而是學會怎麼看、怎麼做、怎麼停，並把整理後的改變接回動作與生活。</p><div className="method-actions"><a className="method-btn method-btn-primary" href="#learning-routes">選擇學習入口</a><Link className="method-btn method-btn-secondary" href="/method/register">登記 Pilot 個別導入</Link></div></header>
  <Section kicker="4R Framework" title="首頁只保留方法骨架，不放完整教材。"><div className="method-framework-grid">{framework.map(([n, en, zh, copy, tag]) => <article className="method-card" key={n}><span className="method-number">{n}</span><h3>{en}｜{zh}</h3><p>{copy}</p><small>{tag}</small></article>)}</div></Section>
  <Section id="learning-routes" kicker="Choose Your Route" title="依照先備能力選擇 Route A／B／C。"><div className="method-route-grid method-route-grid-three">{routes.map((route) => <article className="method-route-card" key={route.en}><span className="method-label">{route.en}</span><h3>{route.label}</h3><p><strong>適合：</strong></p><ul>{route.fit.map((item) => <li key={item}>{item}</li>)}</ul><p><strong>內容：</strong></p><ul>{route.content.map((item) => <li key={item}>{item}</li>)}</ul><p><strong>結果：</strong>{route.result}</p><p className="method-note">{route.note}</p><Link className="method-btn method-btn-secondary" href={route.href}>{route.button}</Link></article>)}</div><div className="method-system-note"><p>BodyFix Method 正在建立分級學習制度。正式課程上線時，將清楚標示學習時數、先備能力、評量方式，以及參與紀錄、實作合格、方法認證與品牌授權的適用範圍。</p><p>目前以 Pilot 個別導入與入門工作坊為主，短期導入與試行活動不等同於 BodyFix 認證或授權。</p></div></Section>
  <Section kicker="Learning Outcomes" title="帶走可記錄、可回測、可延續的服務框架。"><div className="method-outcome-list">{outcomes.map((item, index) => <article className="method-outcome" key={item}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{item}</h3></div></article>)}</div></Section>
  <aside className="portal-boundary method-boundary"><p className="portal-kicker">Safety Boundary</p><h2>先知道不做什麼，方法才有成立的邊界。</h2><div className="method-boundary-grid"><div><h3>BodyFix 會教</h3><p>身體狀態與代償觀察、低痛感外部整理原則、筋膜線與動作回測方法、操作說明、明確同意與停止權、課後追蹤與服務紀錄框架。</p></div><div><h3>BodyFix 不取代</h3><p>醫療診斷與疾病治療、關節矯正或整骨宣稱、內部處理或侵入性操作，以及任何保證改善或永久改變的宣稱。</p></div></div><p className="method-emphasis">我們教判讀，但不把判讀說成診斷；我們教整理，但不把整理包裝成治療。</p></aside>
  <section className="portal-detail-closing method-closing"><p className="portal-kicker">Registration CTA</p><h2>想知道自己適合從哪一條路線開始？</h2><p>先登記 Pilot 個別導入，進行能力盤點、方法導入與個人化學習建議。</p><div className="method-actions"><Link className="method-btn method-btn-primary" href="/method/register">登記 Pilot 個別導入</Link><Link className="method-btn method-btn-secondary" href="/method/pathway">查看制度建置方向</Link></div></section></div></main>;
}
function Section({ id, kicker, title, children }: { id?: string; kicker: string; title: string; children: React.ReactNode }) { return <section id={id} className="portal-detail-section method-section"><div className="portal-detail-heading"><span>{kicker}</span><h2>{title}</h2></div>{children}</section>; }
