import type {
  CommissionRule,
  CustomerOwnershipRule,
  ReferralBonusRule,
  ServiceProduct,
  StaffLevel,
} from "./types";

export const BODYFIX_PRINCIPLES = {
  brandPositioning:
    "BodyFix 是男性身體狀態管理品牌，以判讀、整理、整合、回接與追蹤建立可傳承的服務系統。",
  coreSentence: "讓身體回到更穩定、有韌性、有彈性的系統。",
  operatingLogic:
    "筋膜鏈整理是專業入口，多線整合是進階整理，骨盆核心是深度旗艦，12 次完整計畫是長期系統，培訓、認證與授權是未來槓桿。",
  talentPrinciple:
    "BodyFix 不培養全能員工，而是用同一套品牌主幹，培養不同分支專才。",
  ownershipPrinciple:
    "抽成可以大方，但客戶主檔、預約、收款、紀錄與 CRM 必須進 BodyFix 系統。",
} as const;

export const STAFF_LEVELS: StaffLevel[] = [
  {
    id: "L0_FOUNDATION_ASSISTANT",
    nameZh: "Foundation 助理",
    rank: 0,
    positioning: "接待、清潔、預約、紀錄、場地準備。先學品牌語言與服務邊界，不碰身體技術。",
    canOperateServiceCodes: [],
  },
  {
    id: "L1_GROOMING_TRAINEE",
    nameZh: "Grooming 籌備助理",
    rank: 1,
    positioning:
      "未來男性身體照護與 Grooming 服務入口，目前仍為 coming soon / interest only，不可正式對外操作。",
    canOperateServiceCodes: [],
    notes: ["grooming_interest 不是正式服務，所以 L1 不可直接操作正式收費服務。"],
  },
  {
    id: "L2_OBSERVATION_ASSISTANT",
    nameZh: "跟診觀摩生",
    rank: 2,
    positioning: "旁觀 Gavin 或高階人員示範，協助紀錄，不獨立操作。",
    canOperateServiceCodes: [],
  },
  {
    id: "L3_FASCIA_INTERN",
    nameZh: "筋膜鏈整理實習生",
    rank: 3,
    positioning: "在監督下學習單線筋膜鏈整理，不可獨立代表 BodyFix 接案。",
    canOperateServiceCodes: [],
  },
  {
    id: "L4_FASCIA_LINE_PRACTITIONER",
    nameZh: "筋膜鏈整理師",
    rank: 4,
    positioning: "可獨立操作單次筋膜鏈整理與筋膜線指定整理。",
    canOperateServiceCodes: ["fascia_chain_reset_60", "fascia_line_selected_reset_60"],
  },
  {
    id: "L5_MULTI_LINE_PRACTITIONER",
    nameZh: "多線整合整理師",
    rank: 5,
    positioning: "可處理 2 到 3 條主要張力路徑，進入進階整理。",
    canOperateServiceCodes: ["fascia_chain_reset_60", "fascia_line_selected_reset_60", "multi_line_reset_90"],
  },
  {
    id: "L6_PELVIC_CORE_PRACTITIONER",
    nameZh: "骨盆核心整理師",
    rank: 6,
    positioning:
      "高階權限服務者，可操作骨盆核心整理。重點是同意、遮蔽、安全邊界、判讀與回接。",
    canOperateServiceCodes: [
      "fascia_chain_reset_60",
      "fascia_line_selected_reset_60",
      "multi_line_reset_90",
      "pelvic_core_reset_60",
    ],
    cannotOperateServiceCodes: ["pelvic_core_advanced_120"],
  },
  {
    id: "L7_ADVANCED_INTEGRATION_PRACTITIONER",
    nameZh: "BodyFix 高階整合師",
    rank: 7,
    positioning: "可主導 12 次完整計畫、進階骨盆核心、VIP 深度方案、案例管理與新人培訓。",
    canOperateServiceCodes: [
      "fascia_chain_reset_60",
      "fascia_line_selected_reset_60",
      "multi_line_reset_90",
      "pelvic_core_reset_60",
      "pelvic_core_advanced_120",
      "training_12_foundation",
      "training_24_integration",
      "training_36_progression",
      "training_24_plus_12_bundle",
    ],
  },
  {
    id: "INSTRUCTOR",
    nameZh: "BodyFix 教官",
    rank: 8,
    positioning: "負責工作坊、培訓、認證與授權系統。",
    canOperateServiceCodes: [
      "training_single_session_60",
      "training_12_foundation",
      "training_24_integration",
      "training_36_progression",
      "training_24_plus_12_bundle",
    ],
  },
  {
    id: "GAVIN_ONLY",
    nameZh: "Gavin 本人限定",
    rank: 99,
    positioning: "高風險、高信任、高品牌代表性服務，預設由 Gavin 本人操作或個案判斷。",
    canOperateServiceCodes: [
      "pelvic_core_advanced_120",
      "ziwei_structural_analysis_90",
      "tarot_single_question_15",
      "tarot_status_reading_30",
      "tarot_deep_reading_60",
      "ziwei_tarot_integration_120",
      "consultation_extension_30",
    ],
  },
];

export const SERVICES: ServiceProduct[] = [
  {
    serviceCode: "fascia_chain_reset_60",
    nameZh: "筋膜鏈整理",
    category: "body_reset",
    recommendedPriceTwd: 2200,
    durationMinutes: 60,
    status: "active",
    minimumStaffLevelId: "L4_FASCIA_LINE_PRACTITIONER",
    revenueModel: "service_commission",
    positioning: "BodyFix 專業身體服務入口。",
    externalOneLiner: "不是哪裡痠按哪裡，而是從張力路徑看身體為什麼卡住。",
    nextServiceCodes: ["multi_line_reset_90", "pelvic_core_reset_60", "training_24_plus_12_bundle"],
    defaultMaterialCostTwd: 0,
    defaultAdminCostTwd: 0,
  },
  {
    serviceCode: "fascia_extension_30",
    nameZh: "筋膜鏈延長整理",
    category: "addon",
    recommendedPriceTwd: null,
    durationMinutes: 30,
    status: "active",
    minimumStaffLevelId: "L4_FASCIA_LINE_PRACTITIONER",
    revenueModel: "case_by_case",
    positioning: "筋膜鏈整理加時項目，依現場服務設計個案判斷。",
  },
  {
    serviceCode: "fascia_line_selected_reset_60",
    nameZh: "筋膜線指定整理",
    category: "body_reset",
    recommendedPriceTwd: 2300,
    durationMinutes: 60,
    status: "active",
    minimumStaffLevelId: "L4_FASCIA_LINE_PRACTITIONER",
    revenueModel: "service_commission",
    positioning: "針對特定筋膜線的專業入口。",
    defaultMaterialCostTwd: 0,
    defaultAdminCostTwd: 0,
  },
  {
    serviceCode: "multi_line_reset_90",
    nameZh: "多線整合整理",
    category: "body_reset",
    recommendedPriceTwd: 3600,
    durationMinutes: 90,
    status: "active",
    minimumStaffLevelId: "L5_MULTI_LINE_PRACTITIONER",
    revenueModel: "service_commission",
    positioning: "從單次服務走向系統服務的中間層，適合轉 12 次完整計畫或長期整合。",
    defaultMaterialCostTwd: 0,
    defaultAdminCostTwd: 0,
  },
  {
    serviceCode: "pelvic_core_reset_60",
    nameZh: "骨盆核心整理",
    category: "body_reset",
    recommendedPriceTwd: 2500,
    durationMinutes: 60,
    status: "active",
    minimumStaffLevelId: "L6_PELVIC_CORE_PRACTITIONER",
    revenueModel: "service_commission",
    positioning: "高信任、高邊界要求的深度服務。",
    externalOneLiner: "透過外部評估、筋膜整理、呼吸引導與動作回接，讓骨盆核心回到更穩定的狀態。",
    isHighRiskOrHighTrust: true,
    defaultMaterialCostTwd: 0,
    defaultAdminCostTwd: 0,
  },
  {
    serviceCode: "pelvic_core_extension_30",
    nameZh: "骨盆核心延長整理",
    category: "addon",
    recommendedPriceTwd: null,
    durationMinutes: 30,
    status: "active",
    minimumStaffLevelId: "L6_PELVIC_CORE_PRACTITIONER",
    revenueModel: "case_by_case",
    positioning: "骨盆核心整理加時項目，需依安全邊界與當次狀態個案判斷。",
    isHighRiskOrHighTrust: true,
  },
  {
    serviceCode: "pelvic_core_advanced_120",
    nameZh: "骨盆核心深度完整方案",
    category: "vip",
    recommendedPriceTwd: 6800,
    durationMinutes: 120,
    status: "active",
    minimumStaffLevelId: "GAVIN_ONLY",
    revenueModel: "case_by_case",
    positioning: "高價錨點與品牌高度，不大量開放。",
    isHighRiskOrHighTrust: true,
  },
  {
    serviceCode: "training_24_plus_12_bundle",
    nameZh: "24+12 深度整合方案",
    category: "movement_training",
    recommendedPriceTwd: 60000,
    durationMinutes: null,
    status: "active",
    minimumStaffLevelId: "L7_ADVANCED_INTEGRATION_PRACTITIONER",
    revenueModel: "case_by_case",
    positioning: "教練課與筋膜整理整合的高價長期方案。",
  },
  {
    serviceCode: "grooming_interest",
    nameZh: "熱蠟除毛 / Grooming 興趣登記",
    category: "grooming",
    recommendedPriceTwd: null,
    durationMinutes: null,
    status: "interest_only",
    minimumStaffLevelId: "GAVIN_ONLY",
    revenueModel: "not_open",
    positioning: "未來男性身體照護線，目前只作為興趣登記，不是正式服務。",
    note: "任何 calculator 不應該自動計算 grooming_interest 的服務淨利。",
  },
  {
    serviceCode: "ziwei_structural_analysis_90",
    nameZh: "紫微結構解析",
    category: "status_analysis",
    recommendedPriceTwd: 3600,
    durationMinutes: 90,
    status: "active",
    minimumStaffLevelId: "GAVIN_ONLY",
    revenueModel: "case_by_case",
    positioning: "生命結構與狀態分析分支。",
  },
  {
    serviceCode: "tarot_single_question_15",
    nameZh: "塔羅單題整理",
    category: "status_analysis",
    recommendedPriceTwd: null,
    durationMinutes: 15,
    status: "active",
    minimumStaffLevelId: "GAVIN_ONLY",
    revenueModel: "case_by_case",
    positioning: "單題狀態整理分支。",
  },
  {
    serviceCode: "tarot_status_reading_30",
    nameZh: "塔羅狀態整理",
    category: "status_analysis",
    recommendedPriceTwd: 666,
    durationMinutes: 30,
    status: "active",
    minimumStaffLevelId: "GAVIN_ONLY",
    revenueModel: "case_by_case",
    positioning: "不是替你決定未來，而是幫你看清現在。",
  },
  {
    serviceCode: "tarot_deep_reading_60",
    nameZh: "塔羅深度整理",
    category: "status_analysis",
    recommendedPriceTwd: null,
    durationMinutes: 60,
    status: "active",
    minimumStaffLevelId: "GAVIN_ONLY",
    revenueModel: "case_by_case",
    positioning: "深度狀態整理分支。",
  },
  {
    serviceCode: "ziwei_tarot_integration_120",
    nameZh: "紫微塔羅整合解析",
    category: "status_analysis",
    recommendedPriceTwd: null,
    durationMinutes: 120,
    status: "active",
    minimumStaffLevelId: "GAVIN_ONLY",
    revenueModel: "case_by_case",
    positioning: "結構與當下狀態的整合解析分支。",
  },
  {
    serviceCode: "consultation_extension_30",
    nameZh: "諮詢延長",
    category: "addon",
    recommendedPriceTwd: null,
    durationMinutes: 30,
    status: "active",
    minimumStaffLevelId: "GAVIN_ONLY",
    revenueModel: "case_by_case",
    positioning: "諮詢型服務加時項目。",
  },
  {
    serviceCode: "training_single_session_60",
    nameZh: "單次訓練課",
    category: "movement_training",
    recommendedPriceTwd: null,
    durationMinutes: 60,
    status: "active",
    minimumStaffLevelId: "INSTRUCTOR",
    revenueModel: "training_fee",
    positioning: "動作訓練單堂服務。",
  },
  {
    serviceCode: "training_12_foundation",
    nameZh: "12 次基礎訓練方案",
    category: "movement_training",
    recommendedPriceTwd: null,
    durationMinutes: null,
    status: "active",
    minimumStaffLevelId: "L7_ADVANCED_INTEGRATION_PRACTITIONER",
    revenueModel: "training_fee",
    positioning: "基礎長期動作訓練方案。",
  },
  {
    serviceCode: "training_24_integration",
    nameZh: "24 次整合訓練方案",
    category: "movement_training",
    recommendedPriceTwd: null,
    durationMinutes: null,
    status: "active",
    minimumStaffLevelId: "L7_ADVANCED_INTEGRATION_PRACTITIONER",
    revenueModel: "training_fee",
    positioning: "整合長期動作訓練方案。",
  },
  {
    serviceCode: "training_36_progression",
    nameZh: "36 次進階訓練方案",
    category: "movement_training",
    recommendedPriceTwd: null,
    durationMinutes: null,
    status: "active",
    minimumStaffLevelId: "L7_ADVANCED_INTEGRATION_PRACTITIONER",
    revenueModel: "training_fee",
    positioning: "進階長期動作訓練方案。",
  },
];

export const CUSTOMER_OWNERSHIP_RULES: CustomerOwnershipRule[] = [
  {
    id: "bodyfix_official",
    ownership: "bodyfix",
    crmRequired: true,
    officialPaymentRequired: true,
    note: "官方 IG、官網、LINE、預約系統導入者，客戶主檔歸 BodyFix。",
  },
  {
    id: "staff_own",
    ownership: "shared",
    crmRequired: true,
    officialPaymentRequired: true,
    note: "員工自帶客可提高抽成，但只要使用 BodyFix 場域、品牌或系統，就必須進 BodyFix CRM。",
  },
  {
    id: "partner_referral",
    ownership: "case_by_case",
    crmRequired: true,
    officialPaymentRequired: true,
    note: "合作講師或外部合作導入者，依合作合約拆分。",
  },
  {
    id: "student_own",
    ownership: "student",
    crmRequired: false,
    officialPaymentRequired: false,
    note: "學員回自己場域服務自己的客戶，客戶歸學員，BodyFix 收課程、認證或授權費。",
  },
  {
    id: "unknown",
    ownership: "case_by_case",
    crmRequired: true,
    officialPaymentRequired: true,
    note: "來源未知時先以個案判斷處理，避免自動放行權限或分潤。",
  },
];

export const COMMISSION_RULES: CommissionRule[] = [
  {
    id: "fascia_chain_reset_60_bodyfix_official_L4",
    serviceCode: "fascia_chain_reset_60",
    customerSource: "bodyfix_official",
    staffLevelId: "L4_FASCIA_LINE_PRACTITIONER",
    revenueModel: "service_commission",
    employeeRate: 0.45,
    bodyfixRate: 0.55,
  },
  {
    id: "fascia_line_selected_reset_60_bodyfix_official_L4",
    serviceCode: "fascia_line_selected_reset_60",
    customerSource: "bodyfix_official",
    staffLevelId: "L4_FASCIA_LINE_PRACTITIONER",
    revenueModel: "service_commission",
    employeeRate: 0.45,
    bodyfixRate: 0.55,
  },
  {
    id: "fascia_line_selected_reset_60_staff_own_L4",
    serviceCode: "fascia_line_selected_reset_60",
    customerSource: "staff_own",
    staffLevelId: "L4_FASCIA_LINE_PRACTITIONER",
    revenueModel: "service_commission",
    employeeRate: 0.55,
    bodyfixRate: 0.45,
  },
  {
    id: "multi_line_reset_90_bodyfix_official_L5",
    serviceCode: "multi_line_reset_90",
    customerSource: "bodyfix_official",
    staffLevelId: "L5_MULTI_LINE_PRACTITIONER",
    revenueModel: "service_commission",
    employeeRate: 0.5,
    bodyfixRate: 0.5,
  },
  {
    id: "multi_line_reset_90_staff_own_L5",
    serviceCode: "multi_line_reset_90",
    customerSource: "staff_own",
    staffLevelId: "L5_MULTI_LINE_PRACTITIONER",
    revenueModel: "service_commission",
    employeeRate: 0.55,
    bodyfixRate: 0.45,
  },
  {
    id: "pelvic_core_reset_60_bodyfix_official_L6",
    serviceCode: "pelvic_core_reset_60",
    customerSource: "bodyfix_official",
    staffLevelId: "L6_PELVIC_CORE_PRACTITIONER",
    revenueModel: "service_commission",
    employeeRate: 0.425,
    bodyfixRate: 0.575,
    note: "骨盆核心為高階權限服務，建議員工 40% 到 45%，此處用中位數 42.5%。",
  },
  {
    id: "pelvic_core_reset_60_staff_own_L6",
    serviceCode: "pelvic_core_reset_60",
    customerSource: "staff_own",
    staffLevelId: "L6_PELVIC_CORE_PRACTITIONER",
    revenueModel: "service_commission",
    employeeRate: 0.5,
    bodyfixRate: 0.5,
    note: "高信任服務，員工自帶客可提高抽成，但資料與收款仍需進 BodyFix。",
  },
  {
    id: "pelvic_core_advanced_120_case_by_case",
    serviceCode: "pelvic_core_advanced_120",
    customerSource: "bodyfix_official",
    revenueModel: "case_by_case",
    employeeRate: null,
    bodyfixRate: null,
    note: "120 分鐘深度方案不走一般抽成，優先由 Gavin 或高階整合師個案執行。",
  },
  {
    id: "training_24_plus_12_bundle_case_by_case",
    serviceCode: "training_24_plus_12_bundle",
    customerSource: "bodyfix_official",
    revenueModel: "case_by_case",
    employeeRate: null,
    bodyfixRate: null,
    note: "長期方案不走一般單堂抽成，需依主導者、執行者、轉介者分開計算。",
  },
];

export const REFERRAL_BONUS_RULES: ReferralBonusRule[] = [
  {
    id: "referral_to_fascia_chain_reset_60",
    targetServiceCode: "fascia_chain_reset_60",
    label: "轉成 60 分鐘單次整理",
    bonusMinTwd: 300,
    bonusMaxTwd: 500,
    recommendedBonusTwd: 500,
  },
  {
    id: "referral_to_multi_line_reset_90",
    targetServiceCode: "multi_line_reset_90",
    label: "轉成多線整合",
    bonusMinTwd: 800,
    bonusMaxTwd: 1200,
    recommendedBonusTwd: 1000,
  },
  {
    id: "referral_to_pelvic_core_reset_60",
    targetServiceCode: "pelvic_core_reset_60",
    label: "轉成骨盆核心整理",
    bonusMinTwd: 800,
    bonusMaxTwd: 1500,
    recommendedBonusTwd: 1200,
  },
  {
    id: "referral_to_training_24_plus_12_bundle",
    targetServiceCode: "training_24_plus_12_bundle",
    label: "轉成 24+12 深度整合方案",
    bonusMinTwd: 2000,
    bonusMaxTwd: 5000,
    recommendedBonusTwd: 3000,
  },
];
