import type {
  StaffLevel,
  ServiceProduct,
  CommissionRule,
  ReferralBonusRule,
  CustomerOwnershipRule,
} from "./types";
export const BODYFIX_PRINCIPLES = {
  brandPositioning:
    "BodyFix 是男性身體狀態管理品牌，以判讀、整理、回接、追蹤建立可傳承的服務系統。",
  coreSentence:
    "讓身體回到更穩定、有韌性、有彈性的系統。",
  operatingLogic:
    "Grooming 是低門檻入口，筋膜鏈是專業入口，多線整合是進階整理，骨盆核心是深度旗艦，12 次完整計畫是長期系統，培訓認證授權是未來槓桿。",
  talentPrinciple:
    "BodyFix 不培養全能員工，而是用同一套品牌主幹，培養不同分支專才。",
  ownershipPrinciple:
    "抽成可以大方，但客戶主檔、預約、收款、紀錄與 CRM 必須進 BodyFix 系統。",
} as const;
export const STAFF_LEVELS: StaffLevel[] = [
  {
    id: "L0_FOUNDATION_ASSISTANT",
    nameZh: "Foundation 助理",
    nameEn: "BodyFix Foundation Assistant",
    rank: 0,
    description: "接待、清潔、預約、紀錄、場地準備。先學品牌語言與服務邊界，不碰身體技術。",
    canOperateServiceIds: [],
    cannotOperateNotes: ["不可操作除毛", "不可操作筋膜整理", "不可操作骨盆核心", "不可做訓練指導"],
    upgradeRequirements: ["完成品牌語言訓練", "完成隱私規範訓練", "完成基本服務流程訓練"],
  },
  {
    id: "L1_GROOMING_SPECIALIST",
    nameZh: "Grooming 照護師",
    nameEn: "BodyFix Grooming Specialist",
    rank: 1,
    description: "男性身體照護與除毛服務者，作為低門檻人才入口與信任建立入口。",
    canOperateServiceIds: ["GROOMING_MALE_CARE"],
    cannotOperateNotes: ["不可操作筋膜整理", "不可操作骨盆核心", "不可做訓練指導"],
    upgradeRequirements: ["穩定服務", "無重大客訴", "會做客戶紀錄", "能辨識轉介需求"],
  },
  {
    id: "L2_OBSERVATION_ASSISTANT",
    nameZh: "跟診觀摩生",
    nameEn: "Observation Assistant",
    rank: 2,
    description: "旁觀 Gavin 或高階人員示範，協助紀錄，不獨立操作。",
    canOperateServiceIds: [],
    cannotOperateNotes: ["不可獨立接客", "不可未經同意旁觀", "不可獨立操作身體整理"],
    upgradeRequirements: ["完成觀摩紀錄", "能說明判讀流程", "能說明服務邊界"],
  },
  {
    id: "L3_FASCIA_INTERN",
    nameZh: "筋膜鏈整理實習生",
    nameEn: "Fascia Line Intern",
    rank: 3,
    description: "在監督下練習基礎單線整理，不可獨立代表 BodyFix 接案。",
    canOperateServiceIds: [],
    cannotOperateNotes: ["不可獨立接客", "不可做多線整合", "不可做骨盆核心"],
    upgradeRequirements: ["通過解剖基礎", "通過觸診基礎", "完成服務邊界訓練", "完成案例紀錄"],
  },
  {
    id: "L4_FASCIA_PRACTITIONER",
    nameZh: "筋膜鏈整理師",
    nameEn: "Fascia Line Reset Practitioner",
    rank: 4,
    description: "可獨立操作 1 到 7 單線筋膜鏈指定整理。",
    canOperateServiceIds: ["FASCIA_LINE_RESET_SINGLE"],
    cannotOperateNotes: ["多線整合需再認證", "不可做骨盆核心", "不可主導 12 次完整計畫"],
    upgradeRequirements: ["穩定完成個案", "能做選線判斷", "能寫服務紀錄", "能說明下次方向"],
  },
  {
    id: "L5_MULTI_LINE_PRACTITIONER",
    nameZh: "多線整合整理師",
    nameEn: "Multi-Line Reset Practitioner",
    rank: 5,
    description: "可處理 2 到 3 條主要張力路徑，進入進階整理。",
    canOperateServiceIds: ["FASCIA_LINE_RESET_SINGLE", "MULTI_LINE_RESET"],
    cannotOperateNotes: ["不可做骨盆核心", "不可主導 VIP 方案", "不可主導 12 次完整計畫"],
    upgradeRequirements: ["能判斷主線與副線", "能判斷代償路徑", "能轉介骨盆核心或 12 次計畫"],
  },
  {
    id: "L6_PELVIC_CORE_PRACTITIONER",
    nameZh: "骨盆核心整理師",
    nameEn: "Pelvic Core Reset Practitioner",
    rank: 6,
    description: "高階權限服務者，可操作 BF Pelvic Core 基礎版。",
    canOperateServiceIds: ["FASCIA_LINE_RESET_SINGLE", "MULTI_LINE_RESET", "PELVIC_CORE_RESET"],
    cannotOperateNotes: ["VIP 120 分鐘需 Level 7", "12 次完整計畫主導需 Level 7", "不得越過同意與遮蔽規範"],
    upgradeRequirements: ["通過安全框架", "通過同意流程", "通過紅旗辨識", "完成監督個案"],
  },
  {
    id: "L7_ADVANCED_INTEGRATION_PRACTITIONER",
    nameZh: "BodyFix 高階整合師",
    nameEn: "Advanced Integration Practitioner",
    rank: 7,
    description: "可主導 12 次完整計畫、VIP 深度方案、案例管理與新人培訓。",
    canOperateServiceIds: [
      "FASCIA_LINE_RESET_SINGLE",
      "MULTI_LINE_RESET",
      "PELVIC_CORE_RESET",
      "TWELVE_SESSION_PROGRAM",
      "VIP_DEEP_INTEGRATION_120",
    ],
    cannotOperateNotes: ["授權教官仍需另行認證"],
    upgradeRequirements: ["能做長期規劃", "能做客戶追蹤", "能成交轉單", "能培訓新人"],
  },
  {
    id: "INSTRUCTOR",
    nameZh: "BodyFix 教官",
    nameEn: "BodyFix Instructor",
    rank: 8,
    description: "負責工作坊、培訓、認證與授權系統。",
    canOperateServiceIds: [
      "BODYFIX_TRAINING_SYSTEM",
      "STATUS_READING_SESSION",
      "FASCIA_LINE_RESET_SINGLE",
      "MULTI_LINE_RESET",
      "PELVIC_CORE_RESET",
      "TWELVE_SESSION_PROGRAM",
      "VIP_DEEP_INTEGRATION_120",
    ],
    cannotOperateNotes: [],
    upgradeRequirements: ["能授課", "能評分", "能維護教材", "能維護品牌標準"],
  },
];
export const SERVICES: ServiceProduct[] = [
  {
    id: "GROOMING_MALE_CARE",
    category: "GROOMING",
    nameZh: "BodyFix Grooming｜男性身體照護",
    nameEn: "BodyFix Grooming",
    role: "低門檻入口、員工培訓入口、信任建立入口",
    externalOneLiner: "先從乾淨、舒適與信任開始，建立男性身體照護的第一步。",
    internalPositioning: "Grooming 不是最高技術，但它是最適合養人的入口。",
    recommendedPriceTwd: 2000,
    durationMinutes: null,
    minimumStaffLevelId: "L1_GROOMING_SPECIALIST",
    revenueModel: "service_commission",
    defaultVariableCostTwd: 200,
    defaultAdminCostTwd: 100,
    isHighRiskOrHighTrust: false,
    nextProductIds: ["FASCIA_LINE_RESET_SINGLE", "PELVIC_CORE_RESET", "TWELVE_SESSION_PROGRAM"],
  },
  {
    id: "FASCIA_LINE_RESET_SINGLE",
    category: "FASCIA_LINE",
    nameZh: "BF Fascia Line Reset｜筋膜鏈指定整理",
    nameEn: "BF Fascia Line Reset",
    role: "BodyFix 專業身體服務入口",
    externalOneLiner: "不是哪裡痠按哪裡，而是從張力路徑看身體為什麼卡住。",
    internalPositioning: "專業入口，讓客戶第一次感覺 BodyFix 有判讀、有路徑、有邏輯。",
    recommendedPriceTwd: 2300,
    durationMinutes: 60,
    minimumStaffLevelId: "L4_FASCIA_PRACTITIONER",
    revenueModel: "service_commission",
    defaultVariableCostTwd: 100,
    defaultAdminCostTwd: 100,
    isHighRiskOrHighTrust: false,
    nextProductIds: ["MULTI_LINE_RESET", "PELVIC_CORE_RESET", "TWELVE_SESSION_PROGRAM"],
  },
  {
    id: "MULTI_LINE_RESET",
    category: "MULTI_LINE",
    nameZh: "Multi-Line Reset｜多線整合整理",
    nameEn: "Multi-Line Reset",
    role: "進階整理服務",
    externalOneLiner: "當問題不是單一位置，而是多條張力路徑一起牽動，就需要多線整合。",
    internalPositioning: "從單次服務走向系統服務的中間層，最適合轉 12 次完整計畫。",
    recommendedPriceTwd: 3600,
    durationMinutes: 90,
    minimumStaffLevelId: "L5_MULTI_LINE_PRACTITIONER",
    revenueModel: "service_commission",
    defaultVariableCostTwd: 150,
    defaultAdminCostTwd: 100,
    isHighRiskOrHighTrust: false,
    nextProductIds: ["TWELVE_SESSION_PROGRAM", "PELVIC_CORE_RESET"],
  },
  {
    id: "PELVIC_CORE_RESET",
    category: "PELVIC_CORE",
    nameZh: "BF Pelvic Core｜骨盆核心整理",
    nameEn: "BF Pelvic Core Reset",
    role: "深度旗艦服務",
    externalOneLiner: "透過外部評估、筋膜整理、呼吸引導與動作回接，讓骨盆核心回到更穩定的狀態。",
    internalPositioning: "高權限服務，核心不是做很深，而是邊界、同意、判讀、回接與信任。",
    recommendedPriceTwd: 2500,
    durationMinutes: 60,
    minimumStaffLevelId: "L6_PELVIC_CORE_PRACTITIONER",
    revenueModel: "service_commission",
    defaultVariableCostTwd: 100,
    defaultAdminCostTwd: 100,
    isHighRiskOrHighTrust: true,
    nextProductIds: ["TWELVE_SESSION_PROGRAM", "VIP_DEEP_INTEGRATION_120"],
  },
  {
    id: "TWELVE_SESSION_PROGRAM",
    category: "TWELVE_SESSION_PROGRAM",
    nameZh: "BodyFix 12 次完整計畫",
    nameEn: "BodyFix 12-Session Program",
    role: "長期系統主產品",
    externalOneLiner: "不是單次救火，而是用 12 次建立一條身體狀態重新整理的路線。",
    internalPositioning: "BodyFix 從服務變成資產的主幹產品。",
    recommendedPriceTwd: 36000,
    durationMinutes: null,
    minimumStaffLevelId: "L7_ADVANCED_INTEGRATION_PRACTITIONER",
    revenueModel: "case_by_case",
    defaultVariableCostTwd: 0,
    defaultAdminCostTwd: 0,
    isHighRiskOrHighTrust: true,
    nextProductIds: ["VIP_DEEP_INTEGRATION_120"],
  },
  {
    id: "VIP_DEEP_INTEGRATION_120",
    category: "VIP_INTEGRATION",
    nameZh: "BodyFix VIP 深度完整方案",
    nameEn: "BodyFix VIP Deep Integration",
    role: "高端權限服務",
    externalOneLiner: "給需要更完整判讀、整理與回接的人，一次進入更深層的 BodyFix 整合。",
    internalPositioning: "高價錨點與品牌高度，不大量開放。",
    recommendedPriceTwd: 6800,
    durationMinutes: 120,
    minimumStaffLevelId: "L7_ADVANCED_INTEGRATION_PRACTITIONER",
    revenueModel: "case_by_case",
    defaultVariableCostTwd: 150,
    defaultAdminCostTwd: 100,
    isHighRiskOrHighTrust: true,
    nextProductIds: [],
  },
  {
    id: "BODYFIX_TRAINING_SYSTEM",
    category: "TRAINING",
    nameZh: "BodyFix Training System｜身體狀態整理培訓系統",
    nameEn: "BodyFix Training System",
    role: "未來槓桿收入",
    externalOneLiner: "把 BodyFix 的判讀、整理與回接，整理成可學習、可訓練、可傳承的方法。",
    internalPositioning: "解決 Gavin 休息就沒收入的關鍵路線。",
    recommendedPriceTwd: null,
    durationMinutes: null,
    minimumStaffLevelId: "INSTRUCTOR",
    revenueModel: "training_fee",
    defaultVariableCostTwd: 0,
    defaultAdminCostTwd: 0,
    isHighRiskOrHighTrust: false,
    nextProductIds: [],
  },
  {
    id: "STATUS_READING_SESSION",
    category: "STATUS_READING",
    nameZh: "BF Status Reading｜狀態整理",
    nameEn: "BF Status Reading",
    role: "塔羅、紫微、SADM 的狀態整理分支",
    externalOneLiner: "不是替你決定未來，而是幫你看清現在。",
    internalPositioning: "不要複製命理老師，而是建立 BodyFix 狀態整理工具。",
    recommendedPriceTwd: null,
    durationMinutes: null,
    minimumStaffLevelId: "INSTRUCTOR",
    revenueModel: "case_by_case",
    defaultVariableCostTwd: 0,
    defaultAdminCostTwd: 0,
    isHighRiskOrHighTrust: false,
    nextProductIds: ["BODYFIX_TRAINING_SYSTEM"],
  },
];
export const CUSTOMER_OWNERSHIP_RULES: CustomerOwnershipRule[] = [
  {
    id: "official_customer_bodyfix_owned",
    customerSource: "BODYFIX_OFFICIAL",
    ownership: "BODYFIX",
    crmRequired: true,
    officialPaymentRequired: true,
    note: "官方 IG、官網、LINE、官方預約系統導入者，客戶主檔歸 BodyFix。",
  },
  {
    id: "employee_own_customer_shared",
    customerSource: "EMPLOYEE_OWN",
    ownership: "SHARED",
    crmRequired: true,
    officialPaymentRequired: true,
    note: "員工自帶客可提高抽成，但只要使用 BodyFix 場域、品牌或系統，就必須進 BodyFix CRM。",
  },
  {
    id: "partner_referral_case_by_case",
    customerSource: "PARTNER_REFERRAL",
    ownership: "CASE_BY_CASE",
    crmRequired: true,
    officialPaymentRequired: true,
    note: "合作講師或外部合作導入者，依合作合約拆分。",
  },
  {
    id: "student_own_customer_student_owned",
    customerSource: "STUDENT_OWN",
    ownership: "STUDENT",
    crmRequired: false,
    officialPaymentRequired: false,
    note: "學員回自己場域服務自己的客戶，客戶歸學員，BodyFix 收課程、認證或授權費。",
  },
];
export const COMMISSION_RULES: CommissionRule[] = [
  {
    id: "grooming_official_certified",
    serviceId: "GROOMING_MALE_CARE",
    customerSource: "BODYFIX_OFFICIAL",
    staffLevelId: "L1_GROOMING_SPECIALIST",
    employeeRate: 0.60,
    bodyfixRate: 0.40,
    note: "Grooming 官方客，正式照護師。員工拿高抽成，但資料、收款、紀錄進 BodyFix。",
  },
  {
    id: "grooming_employee_own",
    serviceId: "GROOMING_MALE_CARE",
    customerSource: "EMPLOYEE_OWN",
    staffLevelId: "L1_GROOMING_SPECIALIST",
    employeeRate: 0.65,
    bodyfixRate: 0.35,
    note: "Grooming 員工自帶客，抽成提高，但客戶仍須進官方系統。",
  },
  {
    id: "grooming_intern_official",
    serviceId: "GROOMING_MALE_CARE",
    customerSource: "BODYFIX_OFFICIAL",
    staffLevelId: "L0_FOUNDATION_ASSISTANT",
    employeeRate: 0.45,
    bodyfixRate: 0.55,
    note: "Grooming 實習期或未完全獨立者。",
  },
  {
    id: "fascia_official_certified",
    serviceId: "FASCIA_LINE_RESET_SINGLE",
    customerSource: "BODYFIX_OFFICIAL",
    staffLevelId: "L4_FASCIA_PRACTITIONER",
    employeeRate: 0.45,
    bodyfixRate: 0.55,
    note: "筋膜鏈官方客，通過認證後可獨立操作。",
  },
  {
    id: "fascia_employee_own",
    serviceId: "FASCIA_LINE_RESET_SINGLE",
    customerSource: "EMPLOYEE_OWN",
    staffLevelId: "L4_FASCIA_PRACTITIONER",
    employeeRate: 0.55,
    bodyfixRate: 0.45,
    note: "筋膜鏈員工自帶客，抽成提高，但資料必須進 BodyFix。",
  },
  {
    id: "fascia_intern_supervised",
    serviceId: "FASCIA_LINE_RESET_SINGLE",
    customerSource: "BODYFIX_OFFICIAL",
    staffLevelId: "L3_FASCIA_INTERN",
    employeeRate: 0.30,
    bodyfixRate: 0.70,
    note: "筋膜鏈實習生，需監督，不可獨立代表品牌。",
  },
  {
    id: "multi_line_official",
    serviceId: "MULTI_LINE_RESET",
    customerSource: "BODYFIX_OFFICIAL",
    staffLevelId: "L5_MULTI_LINE_PRACTITIONER",
    employeeRate: 0.50,
    bodyfixRate: 0.50,
    note: "多線整合官方客，進階技術服務。",
  },
  {
    id: "multi_line_employee_own",
    serviceId: "MULTI_LINE_RESET",
    customerSource: "EMPLOYEE_OWN",
    staffLevelId: "L5_MULTI_LINE_PRACTITIONER",
    employeeRate: 0.55,
    bodyfixRate: 0.45,
    note: "多線整合員工自帶客。",
  },
  {
    id: "pelvic_core_official",
    serviceId: "PELVIC_CORE_RESET",
    customerSource: "BODYFIX_OFFICIAL",
    staffLevelId: "L6_PELVIC_CORE_PRACTITIONER",
    employeeRate: 0.425,
    bodyfixRate: 0.575,
    note: "骨盆核心為高階權限服務，建議員工 40% 到 45%，此處用中位數 42.5%。",
  },
  {
    id: "twelve_program_case_by_case",
    serviceId: "TWELVE_SESSION_PROGRAM",
    customerSource: "BODYFIX_OFFICIAL",
    staffLevelId: "L7_ADVANCED_INTEGRATION_PRACTITIONER",
    employeeRate: null,
    bodyfixRate: null,
    note: "12 次完整計畫不走一般抽成，採個案制、主導者分潤或固定獎金。",
  },
  {
    id: "vip_case_by_case",
    serviceId: "VIP_DEEP_INTEGRATION_120",
    customerSource: "BODYFIX_OFFICIAL",
    staffLevelId: "L7_ADVANCED_INTEGRATION_PRACTITIONER",
    employeeRate: null,
    bodyfixRate: null,
    note: "VIP 120 分鐘不走一般抽成，優先由 Gavin 或高階整合師執行。",
  },
];
export const REFERRAL_BONUS_RULES: ReferralBonusRule[] = [
  {
    id: "referral_single_session",
    targetServiceId: "FASCIA_LINE_RESET_SINGLE",
    label: "轉成 60 分鐘筋膜或骨盆核心單次",
    bonusMinTwd: 300,
    bonusMaxTwd: 500,
    recommendedBonusTwd: 500,
    note: "員工發現需求並成功轉介。",
  },
  {
    id: "referral_small_package",
    targetServiceId: "MULTI_LINE_RESET",
    label: "轉成 3 次小方案或進階整理",
    bonusMinTwd: 800,
    bonusMaxTwd: 1200,
    recommendedBonusTwd: 1000,
    note: "實際產品可再細分。",
  },
  {
    id: "referral_twelve_session",
    targetServiceId: "TWELVE_SESSION_PROGRAM",
    label: "轉成 12 次完整計畫",
    bonusMinTwd: 2000,
    bonusMaxTwd: 3000,
    recommendedBonusTwd: 3000,
    note: "高價方案建議固定獎金，不用抽成交比例。",
  },
  {
    id: "referral_vip",
    targetServiceId: "VIP_DEEP_INTEGRATION_120",
    label: "轉成 VIP 進階整合組",
    bonusMinTwd: 3000,
    bonusMaxTwd: 5000,
    recommendedBonusTwd: 5000,
    note: "VIP 若成為長期客，可另設年度管理獎金。",
  },
];
