"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import styles from "./SpaceJune.module.css";
import { CRYSTAL_TYPES, DIRECTIONS, GRID_LABELS, SPACE_TYPES, getAvoidZone, getBirthElement, getElementColor, getGridHighlights, getPlantRec, getRecommendedCrystals, getSunSign } from "@/lib/space-june/space-data";
import { BRANCH_TO_PALACE, BRANCH_TO_STARS, getCurrentPhase, getDajunBranch, getPhaseStrategy, getSanFang } from "@/lib/space-june/dajun-engine";
import { COMBO_PRODUCTS, CONSULT_PACKAGES, READY_PRODUCTS } from "@/lib/space-june/product-catalog";

type View = "home" | "lite" | "pro";
const getQuery = (birth: string, direction: string, space: string) => new URLSearchParams({ birth, direction, space }).toString();

function Header(){return <header className={styles.nav}><div className={`${styles.shell} ${styles.navInner}`}><Link href="/space-june" className={styles.brand}>空間6月<small>Space June · space-june</small></Link><nav className={styles.navLinks}><Link href="/space-june#quiz">開始測驗</Link><Link href="/space-june/category/ready">看方案</Link><Link href="/">BodyFix OS</Link></nav></div></header>}
function BottomNav(){return <nav className={styles.bottomNav}><Link href="/space-june">首頁</Link><Link href="/space-june#quiz">測驗</Link><Link href="/space-june/category/ready">現成款</Link><Link href="/space-june/category/combo">植物＋水晶</Link><Link href="/space-june/category/consult">一對一配置</Link></nav>}
function ProductCard({product}:{product:(typeof READY_PRODUCTS)[number]}){return <article className={styles.card}><span className={styles.pill}>{product.shortTag}</span><h3>{product.name}</h3><p>{product.headline}</p><p><strong>{product.price}</strong></p><Link href={`/space-june/category/${product.categoryKey}`}>了解這個方向 →</Link></article>}

export default function SpaceJuneExperience({view="home",searchParams={}}:{view?:View;searchParams?:Record<string,string|undefined>}){
 const router=useRouter(); const [birth,setBirth]=useState(searchParams.birth||"1990-06-15"); const [direction,setDirection]=useState(searchParams.direction||"東"); const [space,setSpace]=useState(searchParams.space||"work");
 const branch=getDajunBranch(birth); const sanFang=getSanFang(branch); const crystals=getRecommendedCrystals(space,direction); const highlights=getGridHighlights(direction); const query=getQuery(birth,direction,space);
 if(view!=="home") return <main className={styles.page}><Header/><div className={styles.shell}><section className={styles.resultHero}><p className={styles.eyebrow}>空間6月｜{view === "lite" ? "Lite Space Reading" : "Pro 10-Year Rhythm"}</p><h1>{view === "lite" ? `今年先整理「${direction}」的空間節奏` : `${branch}運｜你的 10 年空間節奏`}</h1><p className={styles.lead}>{view === "lite" ? `你的 ${getBirthElement(birth)} 元素與${getSunSign(birth)}節奏，適合用「${getElementColor(getBirthElement(birth))}」作為視覺線索。先理解空間，再決定要不要加入植物、水晶或商品。` : `目前落在 ${getCurrentPhase(birth)}。三方能量把空間分成啟動、建立與整合，不需要一次把整個家改完。`}</p><div className={styles.actions}><Link className={styles.button} href={view === "lite" ? `/space-june/result/pro?${query}` : "/space-june/category/custom"}>{view === "lite" ? "解鎖 Pro 節奏" : "看完整配置"}</Link><Link className={styles.ghost} href="/space-june/category/ready">看現成款</Link></div></section>{view==="lite"?<LiteResult crystals={crystals} highlights={highlights} direction={direction} space={space}/>:<ProResult branch={branch} sanFang={sanFang}/>}</div><BottomNav/></main>;
 return <main className={styles.page}><Header/><div className={styles.shell}><section className={styles.hero}><div><p className={styles.eyebrow}>空間6月｜Space Guide Beta</p><h1>先讀懂空間，<span>再決定放什麼。</span></h1><p className={styles.lead}>用生日、方位與空間用途，整理今年適合你的配置方向。你會先得到生活化的行動，再看植物、水晶與方案。</p><div className={styles.actions}><a className={styles.button} href="#quiz">開始空間測驗</a><Link className={styles.ghost} href="/space-june/result/pro">認識 Pro 節奏</Link></div><div className={styles.tags}><span>生日節奏</span><span>九宮方向</span><span>植物 × 水晶</span></div></div><div className={styles.visual}>{GRID_LABELS.map(x=><div key={x}>{x}</div>)}</div></section><section className={styles.section}><div className={styles.sectionHead}><p className={styles.eyebrow}>Understand before buying</p><h2>不是先逛商城，是先找到空間現在需要的動作。</h2></div><div className={styles.cards}>{SPACE_TYPES.slice(0,3).map(item=><article className={styles.card} key={item.id}><span className={styles.pill}>{item.label}</span><h3>{item.note}</h3><p>從一個角落、一個行動開始，不需要一次完成所有配置。</p></article>)}</div></section><section className={styles.section} id="quiz"><div className={styles.sectionHead}><p className={styles.eyebrow}>Lite Quiz</p><h2>三個選擇，整理你的第一個方向。</h2><p>這不是命定答案，而是一個更容易開始觀察空間的入口。</p></div><form className={styles.quiz} onSubmit={e=>{e.preventDefault();router.push(`/space-june/result/lite?${query}`)}}><div className={styles.field}><label htmlFor="birth">出生日期</label><input id="birth" type="date" value={birth} onChange={e=>setBirth(e.target.value)} required/></div><div className={styles.field}><label>想先整理的方位</label><select value={direction} onChange={e=>setDirection(e.target.value)}>{DIRECTIONS.map(x=><option key={x}>{x}</option>)}</select></div><div className={styles.field}><label>這個空間主要用來做什麼？</label><div className={styles.choiceGrid}>{SPACE_TYPES.map(item=><button type="button" key={item.id} onClick={()=>setSpace(item.id)} className={`${styles.choice} ${space===item.id?styles.choiceActive:""}`}><strong>{item.label}</strong><br/><small>{item.note}</small></button>)}</div></div><button className={styles.button}>查看 Lite 結果</button></form></section><section className={styles.section}><div className={styles.sectionHead}><p className={styles.eyebrow}>After the reading</p><h2>理解之後，再選擇你需要的支持。</h2></div><div className={styles.cards}>{[READY_PRODUCTS[0],COMBO_PRODUCTS[0],CONSULT_PACKAGES[1]].map(p=><ProductCard key={p.id} product={p}/>)}</div></section></div><BottomNav/><footer className={`${styles.shell} ${styles.footer}`}>空間6月 · Space June · version: space-june</footer></main>
}
function LiteResult({crystals,highlights,direction,space}:{crystals:typeof CRYSTAL_TYPES[number][];highlights:number[];direction:string;space:string}){return <div className={styles.resultLayout}><div className={styles.stack}><section className={styles.panel}><p className={styles.eyebrow}>Why this direction</p><h3>先讓「{direction}」成為清楚、可使用的角落</h3><p>{getAvoidZone(direction)}</p><ol><li>先移除三件不屬於這個用途的物品。</li><li>保留一個每天看得到的視覺焦點。</li><li>連續使用七天，再決定是否增加配置。</li></ol></section><section className={styles.panel}><h3>植物與水晶方向</h3><div className={styles.recommendations}><div><strong>植物</strong><p>{getPlantRec(space)}</p></div>{crystals.map(c=><div key={c.id}><strong>{c.name} · {c.crystal}</strong><p>{c.description}</p><Link href={`/space-june/crystals/${c.id}`}>看完整說明 →</Link></div>)}</div></section></div><aside className={styles.panel}><p className={styles.eyebrow}>Nine-grid focus</p><div className={styles.grid}>{GRID_LABELS.map((x,i)=><div key={x} className={`${styles.gridCell} ${highlights.includes(i)?styles.gridCellActive:""}`}>{x}</div>)}</div><h3>適合材質</h3><p>木、霧面陶器、天然纖維；避免一次加入太多高反光物件。</p></aside></div>}
function ProResult({branch,sanFang}:{branch:string;sanFang:string[]}){return <div className={styles.resultLayout}><section className={styles.panel}><p className={styles.eyebrow}>San Fang Energy</p><h3>{BRANCH_TO_PALACE[branch]} · 三方能量三角形</h3><div className={styles.triangle}>{sanFang.map(x=><span key={x}>{x} · {BRANCH_TO_STARS[x]?.[0]}</span>)}</div><p>三個節點不是三個要同時完成的任務，而是用來檢查空間是否同時具有啟動、支持與收斂。</p></section><section className={styles.stack}>{[0,1,2].map(i=>{const x=getPhaseStrategy(i);const b=sanFang[i];return <article className={styles.panel} key={x.phase}><span className={styles.pill}>{x.phase} · {b}</span><h3>{BRANCH_TO_STARS[b]?.join(" × ")}</h3><p><strong>空間動作：</strong>{x.action}</p><p>植物：{x.plant} · 水晶：{x.crystal}</p></article>})}</section></div>}
